### ISSUE TITLE
Add very basic CI

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/atomicow#4]
We just need cargo test, cargo clippy and cargo format.

**Comment by BD103** [comment]
There are no unit tests so far, so running `cargo test` is somewhat pointless, but that can be changed!

**Comment by mnmaita** [comment]
I'll be working on this tomorrow.

**Comment by BD103** [comment]
> I'll be working on this tomorrow.

Ping me when its ready, I'll review it!
