### ISSUE TITLE
Add crate-level docs / README

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/atomicow#7]
This should be written in README.md, and get ported automatically to the crate docs using the include_str macro.

> [4:49 PM]cart: I think about it as: "CowArc + support for allocation-free static strings w/ From<&'static str> impls that preserve the static lifetime across clones"

**Comment by mnmaita** [comment]
@alice-i-cecile should we replace the current description in the README with the one from Cart, or should we add it?

Also, I don't have any experience with docs generation, so where can I find some examples or guidelines to port them properly?

**Comment by alice-i-cecile** [comment]
I'm tackling this now; I'll ping you for review!
